swagger: "2.0"
info:
  version: "0.0.1"
  title: aws-sample
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /version:
    get:
      description: Returns version
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VersionResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  VersionResponse:
    required:
      - apiversion
    properties:
      apiversion:
        type: string
  ErrorResponse:
    required:
      - errorcode
    properties:
      errorcode:
        type: string
