Resources:
  APIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'jcnix-api-dev'
  APIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 'jcnix-api-dev'
      PolicyDocument:
        Statement:
          - Sid: 'Allow Jenkins to upload'
            Action:
              - 's3:List*'
              - 's3:Put*'
              - 's3:Delete*'
            Effect: Allow
            Resource: 
              - 'arn:aws:s3:::jcnix-api-dev'
              - 'arn:aws:s3:::jcnix-api-dev/*'
            Principal: 
              AWS: 'arn:aws:iam::965128151894:user/jenkins'
    DependsOn:
      - APIBucket
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AWSLambdaExecute
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
    Application:
      Type: AWS::Lambda::Function
      Properties:
        Runtime: nodejs14.x
        Role: arn:aws:iam::965128151894:role/lambda-role
        Handler: index.handler
        Code:
          S3Bucket: 'jcnix-api-dev'
          S3Key: 'api.zip'
