Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'lambda-role'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  Application:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Role: arn:aws:iam::965128151894:role/lambda-role
      Handler: index.handler
      Code:
        S3Bucket: 'jcnix-api-dev'
        S3Key: 'api.zip'
      DependsOn:
        - LambdaRole
